apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: Kubernetes.io/gce-pd # exemplo do google cloud
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none